apiVersion: db.breeze.sh/v1alpha1
kind: User
metadata:
  name: user-sample
spec:
  username: example
  host: '%'
  secretName: example-db-credentials
  grants:
    - target: 'example.*'
      privileges: ['*']
