apiVersion: db.breeze.sh/v1alpha1
kind: User
metadata:
  name: user-sample
spec:
  username: leo
  host: '%'
  secretName: leo-db-credentials
  grants:
    - target: 'jobilla.*'
      privileges: ['*']
